PacketDct = \
{7: {'ValueRange': [0, 31],
  'dtype': 'B',
  'id': 7,
  'name': 'BumpsAndWheelDrops',
  'size': 1,
  'units': None},
 8: {'ValueRange': [0, 1],
  'dtype': 'B',
  'id': 8,
  'name': 'Wall',
  'size': 1,
  'units': None},
 9: {'ValueRange': [0, 1],
  'dtype': 'B',
  'id': 9,
  'name': 'CliffLeft',
  'size': 1,
  'units': None},
 10: {'ValueRange': [0, 1],
  'dtype': 'B',
  'id': 10,
  'name': 'CliffFrontLeft',
  'size': 1,
  'units': None},
 11: {'ValueRange': [0, 1],
  'dtype': 'B',
  'id': 11,
  'name': 'CliffFrontRight',
  'size': 1,
  'units': None},
 12: {'ValueRange': [0, 1],
  'dtype': 'B',
  'id': 12,
  'name': 'CliffRight',
  'size': 1,
  'units': None},
 13: {'ValueRange': [0, 1],
  'dtype': 'B',
  'id': 13,
  'name': 'VirtualWall',
  'size': 1,
  'units': None},
 14: {'ValueRange': [0, 31],
  'dtype': 'B',
  'id': 14,
  'name': 'Overcurrents',
  'size': 1,
  'units': None},
 15: {'ValueRange': [0, 0],
  'dtype': 'B',
  'id': 15,
  'name': 'Unused',
  'size': 1,
  'units': None},
 16: {'ValueRange': [0, 0],
  'dtype': 'B',
  'id': 16,
  'name': 'Unused',
  'size': 1,
  'units': None},
 17: {'ValueRange': [0, 255],
  'dtype': 'B',
  'id': 17,
  'name': 'IRByte',
  'size': 1,
  'units': None},
 18: {'ValueRange': [0, 15],
  'dtype': 'B',
  'id': 18,
  'name': 'Buttons',
  'size': 1,
  'units': None},
 19: {'ValueRange': [-32768, 32767],
  'dtype': 'h',
  'id': 19,
  'name': 'Distance',
  'size': 2,
  'units': None},
 20: {'ValueRange': [0, 5],
  'dtype': 'h',
  'id': 20,
  'name': 'Angle',
  'size': 2,
  'units': None},
 21: {'ValueRange': [0, 5],
  'dtype': 'B',
  'id': 21,
  'name': 'ChargingState',
  'size': 1,
  'units': None},
 22: {'ValueRange': [-32768, 32767],
  'dtype': 'H',
  'id': 22,
  'name': 'Voltage',
  'size': 2,
  'units': None},
 23: {'ValueRange': [-32768, 32767],
  'dtype': 'h',
  'id': 23,
  'name': 'Current',
  'size': 2,
  'units': None},
 24: {'ValueRange': [-128, 127],
  'dtype': 'b',
  'id': 24,
  'name': 'BatteryTemperature',
  'size': 1,
  'units': None},
 25: {'ValueRange': [0, 65535],
  'dtype': 'H',
  'id': 25,
  'name': 'BatteryCharge',
  'size': 2,
  'units': None},
 26: {'ValueRange': [0, 4095],
  'dtype': 'H',
  'id': 26,
  'name': 'BatteryCapacity',
  'size': 2,
  'units': None},
 27: {'ValueRange': [0, 4095],
  'dtype': 'H',
  'id': 27,
  'name': 'WallSignal',
  'size': 2,
  'units': None},
 28: {'ValueRange': [0, 4095],
  'dtype': 'H',
  'id': 28,
  'name': 'CliffLeftSignal',
  'size': 2,
  'units': None},
 29: {'ValueRange': [0, 4095],
  'dtype': 'H',
  'id': 29,
  'name': 'CliffFrontLeftSignal',
  'size': 2,
  'units': None},
 30: {'ValueRange': [0, 4095],
  'dtype': 'H',
  'id': 30,
  'name': 'CliffFrontRightSignal',
  'size': 2,
  'units': None},
 31: {'ValueRange': [0, 4095],
  'dtype': 'H',
  'id': 31,
  'name': 'CliffRightSignal',
  'size': 2,
  'units': None},
 32: {'ValueRange': [0, 31],
  'dtype': 'B',
  'id': 32,
  'name': 'UserDigitalInputs',
  'size': 1,
  'units': None},
 33: {'ValueRange': [0, 1023],
  'dtype': 'B',
  'id': 33,
  'name': 'UserAnalogInput',
  'size': 2,
  'units': None},
 34: {'ValueRange': [0, 3],
  'dtype': 'B',
  'id': 34,
  'name': 'ChargingSourcesAvailable',
  'size': 1,
  'units': None},
 35: {'ValueRange': [0, 3],
  'dtype': 'B',
  'id': 35,
  'name': 'OIMode',
  'size': 1,
  'units': None},
 36: {'ValueRange': [0, 15],
  'dtype': 'B',
  'id': 36,
  'name': 'SongNumber',
  'size': 1,
  'units': None},
 37: {'ValueRange': [0, 1],
  'dtype': 'B',
  'id': 37,
  'name': 'SongPlaying',
  'size': 1,
  'units': None},
 38: {'ValueRange': [0, 42],
  'dtype': 'B',
  'id': 38,
  'name': 'NumberOfStreamPackets',
  'size': 1,
  'units': None},
 39: {'ValueRange': [-500, 500],
  'dtype': 'h',
  'id': 39,
  'name': 'Velocity',
  'size': 2,
  'units': None},
 40: {'ValueRange': [-32768, 32767],
  'dtype': 'h',
  'id': 40,
  'name': 'Radius',
  'size': 2,
  'units': None},
 41: {'ValueRange': [-500, 500],
  'dtype': 'h',
  'id': 41,
  'name': 'RightVelocity',
  'size': 2,
  'units': None},
 42: {'ValueRange': [-500, 500],
  'dtype': 'h',
  'id': 42,
  'name': 'LeftVelocity',
  'size': 2,
  'units': None}}
